<a href="https://colab.research.google.com/github/GaneshPechetti/FML/blob/main/KNN_on_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#importing libraries

import numpy as np
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
#loading the dataset
iris = load_iris()

In [3]:
iris.data[:5]


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [4]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [5]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [10]:
type(iris)

sklearn.utils._bunch.Bunch

In [11]:
type(iris.data), type(iris.target)

(numpy.ndarray, numpy.ndarray)

In [12]:
iris.data.shape


(150, 4)

In [13]:
X_train, X_test, y_train, y_test = train_test_split(iris.data,iris.target,test_size=0.2,random_state=41)

In [14]:
X_train.shape, X_test.shape

((120, 4), (30, 4))

In [15]:
y_train.shape, y_test.shape

((120,), (30,))

In [44]:
knn1 = KNeighborsClassifier(n_neighbors = 1)
knn1.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [45]:
y_pred = knn1.predict(X_test)

In [46]:
knn1.score(X_train, y_train), knn1.score(X_test,y_test)

(1.0, 0.9)

In [47]:
print(confusion_matrix(y_test, y_pred))
print()
print(classification_report(y_test,y_pred))

[[ 9  0  0]
 [ 0 10  1]
 [ 0  2  8]]

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.83      0.91      0.87        11
           2       0.89      0.80      0.84        10

    accuracy                           0.90        30
   macro avg       0.91      0.90      0.90        30
weighted avg       0.90      0.90      0.90        30



In [48]:
knn3 = KNeighborsClassifier(n_neighbors = 3)
knn3.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [49]:
y_pred = knn3.predict(X_test)

In [50]:
knn3.score(X_train, y_train), knn3.score(X_test,y_test)

(0.975, 0.9333333333333333)

In [51]:
print(confusion_matrix(y_test, y_pred))
print()
print(classification_report(y_test,y_pred))

[[ 9  0  0]
 [ 0 10  1]
 [ 0  1  9]]

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.91      0.91      0.91        11
           2       0.90      0.90      0.90        10

    accuracy                           0.93        30
   macro avg       0.94      0.94      0.94        30
weighted avg       0.93      0.93      0.93        30



In [52]:
knn5 = KNeighborsClassifier(n_neighbors = 5)
knn5.fit(X_train, y_train)

KNeighborsClassifier()

In [53]:
y_pred = knn5.predict(X_test)

In [54]:
knn5.score(X_train, y_train), knn5.score(X_test,y_test)

(0.9833333333333333, 0.9666666666666667)

In [55]:
print(confusion_matrix(y_test, y_pred))
print()
print(classification_report(y_test,y_pred))

[[ 9  0  0]
 [ 0 10  1]
 [ 0  0 10]]

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      0.91      0.95        11
           2       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

